# SPDX-FileCopyrightText: 2022 Alec Delaney, written for Adafruit Industries
# SPDX-FileCopyrightText: Copyright (c) 2025 Ben Robinson for CodingFlow
#
# SPDX-License-Identifier: MIT

[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
]

[project]
name = "circuitpython-pixel-mapper"
description = "Pixel Mapper for Adafruit_CircuitPython_LED_Animation"
version = "v1.0.2"
readme = "README.rst"
authors = [
    {name = "CodingFlow", email = "ben@codingflow.dev"}
]
urls = {Homepage = "https://github.com/clickonben/CircuitPython_pixel_mapper"}
keywords = [
    "adafruit",
    "blinka",
    "circuitpython",
    "micropython",
    "pixel_mapper",
    "LED",
    "neopixel",
    "ws2812b",
    "animation",
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Hardware",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
# TODO: IF LIBRARY FILES ARE A PACKAGE FOLDER,
#       CHANGE `py_modules = ['...']` TO `packages = ['...']`
py-modules = ["pixel_mapper"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {optional = {file = ["optional_requirements.txt"]}}
