[project]
name = "mseep-mcp-aiven"
version = "0.1.6"
description = "An MCP server for Aiven."
readme = "README.md"
license = "Apache-2.0"
license-files = [
    "LICENSE",
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.3.0",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
    "aiven-client>=4.5.1",
    "pip-system-certs>=4.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
mcp-aiven = "mcp_aiven.main:main"

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
]

[tool.hatch.build.targets.wheel]
packages = [
    "mcp_aiven",
]

[tool.ruff]
line-length = 101

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
