[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "burdenoff-common"
version = "0.1.0"
authors = [
    {name = "Burdenoff Team", email = "info@burdenoff.com"},
]
description = "Python SDK for Burdenoff Workspace Server"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.0",
    "gql>=3.0.0",
    "graphql-core>=3.1.0",
    "pyjwt>=2.0.0",
]

[project.urls]
"Homepage" = "https://github.com/burdenoff/burdenoff-common"
"Bug Tracker" = "https://github.com/burdenoff/burdenoff-common/issues" 