[project]
name = "mseep-dappier-mcp"
version = "0.3.3"
description = "An MCP server for interacting with Dappier's RAG models"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]
keywords = [
    "http",
    "mcp",
    "llm",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "dappier>=0.3.3",
    "mcp[cli]>=1.2.1",
    "pydantic>=2.10.2",
]

[project.scripts]
dappier-mcp = "dappier_mcp:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets]
