[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "openstack-toolbox"
version = "1.3.2"
authors = [
    { name="Loutre", email="loutre@ikmail.com" },
]
description = "A toolbox for OpenStack (Infomaniak hosting)"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
License = "Apache-2.0"
license-files = ["LICENCE*"]

[project.urls]
Homepage = "https://github.com/ClaraVnk/openstack-toolbox"
Issues = "https://github.com/ClaraVnk/openstack-toolbox/issues"

[project.scripts]
openstack_summary = "src.openstack_summary:main"
openstack_optimization = "src.openstack_optimization:main"
weekly_notification_optimization = "src.weekly_notification_optimization"

[tool.hatch.build.targets.sdist]
exclude = [
    "/bin/python3",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]