[project]
name = "mseep-itmcp"
version = "0.1.2"
description = "MCP server enabling AI assistants to execute terminal commands through a secure shell interface"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
license = "MIT"
dependencies = [
    "mcp>=1.0.0",
]
requires-python = ">=3.10"
readme = "README.md"
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets]
