[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "uniform-vlm"
version = "0.1.2"
description = "Easy oneâ€‘liner training + inference tool for the uniform LoRA VLM."
readme = "README.md"
authors = [
  {name = "Dillon Murphy", email = "ddmurphy@calpoly.edu"},
  {name = "Kailyn Kragas", email = "kkragas@calpoly.edu"},
  {name = "Sofia Bryukhova", email = "sbryukho@calpoly.edu"},
  {name = "Jasmine Cabrera", email = "jkscabrera2003@gmail.com"}
]
requires-python = ">=3.9"
dependencies = [
  "pandas>=2.0",
  "huggingface_hub>=0.22",
  "transformers>=4.39",
  "ms-swift"
]

[project.scripts]
uniform-vlm = "uniform_vlm.cli:main"

