[project]
name = "mseep-markitdown-mcp-server"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
requires-python = ">=3.12"
dependencies = [
    "markitdown>=0.1",
    "mcp>=1.2.1",
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
markitdown = "markitdown_mcp_server:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "off"
reportOptionalMemberAccess = false

[tool.hatch.build.targets]
