# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "refrakt_core"
version = "0.1.1"
description = "A modular library for training, benchmarking, and experimenting with deep vision models."
readme = "README.md"
authors = [
    { name = "Akshath Mangudi", email = "akshathmangudi@gmail.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0",
    "torchvision",
    "einops",
    "matplotlib",
    "numpy",
    "requests",
    "pillow",
    "tqdm"
]

[project.urls]
"Homepage" = "https://github.com/refrakt-hub/refrakt_core"
"Bug Tracker" = "https://github.com/yourusername/refrakt_core/issues"

[tool.setuptools.packages.find]
where = ["src"]
