[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "mseep-mcp-server-aws-resources"
version = "0.1.2"
description = "MCP server for AWS resources using boto3"
requires-python = ">=3.10"
dependencies = [
    "boto3",
    "mcp",
    "pydantic",
    "pytz",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/mcp_server_aws_resources",
]
