[project]
name = "mcpx-eval"
version = "0.4.2"
description = "Open ended tool use evaluation framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.5",
    "matplotlib>=3.10.0",
    "mcp-run>=0.5.0",
    "mcpx-py>=0.7.0",
    "pandas>=2.2.0",
    "pystache>=0.6.7",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "python-lsp-ruff>=2.2.2",
    "python-lsp-server>=1.12.2",
    "ruff>=0.9.6",
]

[project.scripts]
mcpx-eval = "mcpx_eval.__main__:main"

# Workaround for uv/setuptools version mismatch
# https://github.com/astral-sh/uv/issues/9513#issuecomment-2519527822
[tool.setuptools]
license-files = []
