[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "mseep-mcp_doc_scraper"
version = "0.1.2"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
description = "MCP server for scraping documentation"
requires-python = ">=3.7"
dependencies = [
    "aiohttp",
    "mcp",
    "pydantic",
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[tool.setuptools]
packages = [
    "mcp_doc_scraper",
]
