[project]
name = "emoji_logger"
version = "0.1.17"
description = "Custom python logging module"
authors = [{ name = "KyungHo Kim", email = "qqaa3030@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = ["pre-commit>=4.1.0", "pytest>=8.3.4", "pytest-cov>=6.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["emoji_logger"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "--cov=emoji_logger --cov-report=term-missing"
