[project]
name = "mseep-zotero-mcp"
version = "0.1.8"
description = "Model Context Protocol server for Zotero"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
readme = "README.md"
requires-python = ">=3.11"
keywords = [
    "mcp",
    "zotero",
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]
dependencies = [
    "mcp[cli]>=1.2.1",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
    "pyzotero>=1.6.8",
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.license]
file = "LICENSE"

[project.scripts]
zotero-mcp = "zotero_mcp.cli:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.4",
]

[tool.hatch.build.targets]
