[tool.poetry]
name = "kvcommon"
version = "0.3.7"
description = "Library of miscellaneous common python utils that aren't worthy of their own dedicated libs."
authors = ["Rob Voigt <code@ravoigt.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/RAVoigt/kvcommon"
repository = "https://github.com/RAVoigt/kvcommon"

[build-system]
requires = ["poetry-core>=1.0.0"] # Poetry 1.x style; not PEP 621
build-backend = "poetry.core.masonry.api"

# ================================
# Tools etc.
[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

# ================================
# Dependencies
[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"

# ==== Extras

# Flask
flask = { version = "^3.1.0", optional = true }
flask-http-middleware = { version = "^0.4.2", optional = true }
flask-apscheduler = { version = "^1.13.1", optional = true }
jinja2 = { version = "^3.1.6", optional = true }  # Pin minimum version for CVE, until Flask updates

# K8s
kubernetes = { version = "^31.0.0", optional = true }

# Metrics
prometheus-client = { version = "^0.20.0", optional = true }
prometheus-flask-exporter = { version = "^0.23.1", optional = true }

# Traces
opentelemetry-exporter-otlp = { version = "*", optional = true } # TODO
opentelemetry-instrumentation-flask = { version = "*", optional = true } # TODO
opentelemetry-instrumentation-logging = { version = "*", optional = true } # TODO

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "*"
ipdb = "*"
ipython = "*"
mock = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pyfakefs = "*"

[tool.poetry.extras]
flask = ["flask", "flask-http-middleware", "flask-apscheduler", "jinja2"]
k8s = ["kubernetes"]
metrics = ["prometheus-client", "prometheus-flask-exporter"]
traces = ["opentelemetry-exporter-otlp", "opentelemetry-instrumentation-logging", "opentelemetry-instrumentation-flask"]
