[tool.poetry]
name = "StereotacticFrame"
version = "0.4.2"
description = "A package to register MR and CT images to frame space"
authors = ["dwml <dwm.loeffen@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
SimpleITK = "^2.3.1"
pyvista = "^0.44.0"
typer = "^0.12.5"
numpy = "^1.26.0"

[tool.poetry.dev-dependencies]
flake8 = "^7.1.0"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
pytest-profiling = "^1.7.0"

[tool.poetry.scripts]
frame_transform = "stereotacticframe.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
