[project]
dependencies = [
    "anyio==4.9.0",
    "art==6.5",
    "attrs==25.3.0",
    "bids2table==2.0.0",
    "bidsschematools==1.0.3",
    "blinker==1.9.0",
    "cachetools==5.5.2",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "chardet==5.2.0",
    "charset-normalizer==3.4.1",
    "click==8.2.0",
    "colorama==0.4.6",
    "contourpy==1.3.1",
    "cryptography==44.0.1",
    "css-html-js-minify==2.5.5",
    "cssselect==1.3.0",
    "cssutils==2.11.1",
    "cycler==0.12.1",
    "DateTime==5.5",
    "docutils==0.21.2",
    "elbow==0.1.1",
    "filelock==3.18.0",
    "fonttools==4.56.0",
    "h11==0.16.0",
    "hishel==0.1.2",
    "htmlmin==0.1.12",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "idna==3.10",
    "Jinja2==3.1.6",
    "joblib==1.4.2",
    "jsonschema==4.23.0",
    "kaleido==0.2.1",
    "kiwisolver==1.4.8",
    "lxml==5.3.1",
    "markdown-it-py==3.0.0",
    "MarkupSafe==3.0.2",
    "matplotlib==3.10.0",
    "mdurl==0.1.2",
    "msgpack==1.1.0",
    "nh3==0.2.21",
    "nibabel==5.3.2",
    "nilearn==0.11.1",
    "numpy==2.2.3",
    "packaging==24.2",
    "pandas==2.2.3",
    "pillow==11.1.0",
    "plotly==6.1.0",
    "premailer==3.10.0",
    "pyarrow==19.0.0",
    "pycparser==2.22",
    "Pygments==2.19.1",
    "pyparsing==3.2.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "pytz==2025.1",
    "PyYAML==6.0.2",
    "reportlab==4.3.1",
    "requests==2.32.3",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "six==1.17.0",
    "sniffio==1.3.1",
    "socksio==1.0.0",
    "threadpoolctl==3.5.0",
    "tomlkit==0.13.2",
    "tqdm==4.67.1",
    "typing_extensions==4.12.2",
    "tzdata==2025.1",
    "urllib3==2.3.0",
    "zope.interface==7.2",
]
name = "CPACqc"
version = "0.2.16"
description = "A BIDS QC report generator"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Biraj Shrestha", email = "birajstha@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/birajstha/bids_qc"

[project.scripts]
cpacqc = "CPACqc.ui.cli:run"

[tool.pdm]
distribution = true

[tool.pdm.build]
includes = [
    "CPACqc",
    "README.md",
    "static",
]

[tool.pdm.dev-dependencies]
test = [
    "pytest",
]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "CPACqc/tests",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
