[project]
name = "mseep-choose-mcp-server"
version = "0.1.12"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "google-cloud-bigquery>=3.29.0",
    "mcp[cli]>=1.3.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
choose-mcp-server = "main:run"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
