[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "mseep-mcp_metal_price"
version = "0.0.6"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
description = "An MCP server for metal price information"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.0.0",
    "requests>=2.31.0",
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
mcp_metal_price = "src.mcp_metal_price.server:main"
