[project]
name = "funcall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Jianqi Pan", email = "jannchie@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["openai>=1.79.0", "pydantic>=2.11.4", "rich>=14.0.0"]
keywords = ["function call", "openai", "pydantic", "rich", "AI", "tooling"]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pyright]

[tool.ruff]
line-length = 200

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "PGH",
    "RUF003",
    "BLE001",
    "ERA001",
    "FIX002",
    "TD002",
    "TD003",
    "D",
    "PLR2004", # Allow Magic Numbers
    "INP001",  # Allow without __init__.py
    "N812",    # Allow aliased to non-lowercase names (e.g. `import torch.nn.functional as F`)
    "FBT003",  # Allow boolean positional values in function calls
    "S311",    # Allow use random
    "ANN201",  # Allow no return type
    "RUF012",
    "T201",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*" = ["S101"]

[tool.uv]
upgrade = true
package = true

[dependency-groups]
dev = ["ruff>=0.11.10"]
