[project]
name = "lumafit"
version = "0.2.0"
description = "A Numba-accelerated Levenberg-Marquardt fitting library"
readme = "README.md"
authors = [{ name = "Mirza Arnaut", email = "mirza.arnaut@tu-dortmund.de" }]
license = { text = "MIT" }
keywords = [
  "levenberg-marquardt",
  "numba",
  "optimization",
  "fitting",
  "least-squares",
  "scientific",
]
requires-python = ">=3.10"
dependencies = ["numpy>=2.2.5", "numba>=0.61.0", "scipy>=1.15.3"]

[dependency-groups]
docs = [
  "myst-parser>=4.0.1",
  "pydata-sphinx-theme>=0.16.1",
  "sphinx-autoapi>=3.6.0",
  "sphinx-autodoc-typehints>=3.0.1",
  "sphinx-copybutton>=0.5.2",
  "sphinx>=8.1.3",
  "sphinxcontrib-bibtex>=2.6.3",
  "sphinxcontrib-napoleon>=0.7",
  "linkify-it-py>=2.0.3",
  "setuptools>=61.0",
]
test = ["pytest>=8.3.3", "pytest-cov>=6.1.1"]

[tool.pytest.ini_options]
minversion = "8.0"
# addopts = "-ra -q"
log_cli = true
log_level = "INFO"
log_format = "%(asctime)s - %(name)-8s - %(levelname)s - %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = ["tests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# [build-system]
# requires = ["setuptools>=61.0", "wheel"]
# build-backend = "setuptools.build_meta"
# backend-path = "."

[semantic_release]
version_variable = ["lumafit/__init__.py:__version__"]
version_toml = ["pyproject.toml:project.version:nf"]
major_on_zero = false
branch = "main"
build_command = "curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env && uv build"
