[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "suhaspuranik"
version = "0.1.3"
description = "A simple greeting package"
authors = [
    { name = "suhaspuranika", email = "suhas.puranik@dataprowess.com.au" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/suhaspuranika/mypackage"
