[tool.poetry]
name = "calendar-agent"
version = "1.0.1"
description = "Control Google Calendar using OpenAI Agents"
authors = ["Jimming Cheng <jimming@gmail.com>"]
readme = "README.md"
packages = [{include = "calendar_agent"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = ">=1.78.1,<2.0.0"
openai-agents = ">=0.0.15,<1.0.0"
google-api-python-client = ">=2.169.0,<3.0.0"
oauth2client = ">=4.1.3,<5.0.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
