[project]
name = "arc-agi"
version = "0.0.6"
requires-python = ">=3.12"
dependencies = [
    "arc-agi-core",
]

[project.optional-dependencies]
all = ["arc-agi-dsl","arc-agi-llm"]
dsl = ["arc-agi-dsl"]
llm = ["arc-agi-llm"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/arc_agi"]

[tool.uv.sources]
arc-agi-core = { workspace = true }
arc-agi-dsl = { workspace = true }
arc-agi-llm = { workspace = true }