[project]
name = "mseep-overseerr-mcp"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "python-dotenv>=1.0.0",
    "requests>=2.32.3",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
overseerr-mcp = "overseerr_mcp:main"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
