[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "query_using_methods"
version = "0.0.1"
authors = [
  { name="Buzurgmexr Sultonaliyev", email="buzurgmexrubon@gmail.com" },
]
description = "Build your queries using methods (works like LINQ)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [           
    "loguru>=0.7.3",
    "asyncpg>=0.30.0",
    "pytz>=2025.2",
]

[tool.setuptools.packages.find]
where = ["."]