[tool.poetry]
name = "oak_cli"
version = "0.5.2"
description = "The Oakestra CLI"
authors = ["Alexander Malyuk <malyuk.alexander1999@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
pydantic = "^2.6.4"
icecream = "^2.1.3"
typer = "^0.15.4"
rich-pixels = "^3.0.1"
ansible = "^10.1.0"
ansible-core = "^2.17.1"
ansible-runner = "^2.4.0"
psutil = "^5.9.8"
# NOTE: This works great for development.

# But Pypi (pip) does not allow such dependencies.
# oakestra_utils = { git = "https://github.com/oakestra/oakestra.git@develop", subdirectory = "libraries/oakestra_utils_library" }
oakestra-utils = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
oak = "oak_cli.main:main"

[tool.ruff]
line-length = 100
[tool.ruff.lint]
extend-select = [
    "TD",  # todos
    "I",  # isort
]
ignore = [
    "TD003",  # missing-todo-link. Ignored because we don't require adding tickets to TODOs
]
