[project]
name = "snsr"
version = "0.1.2"
description = "A simple random movement screensaver."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyautogui>=0.9.54",
]

[project.scripts]
snsr = "main:run_screensaver"

[project.urls]
Homepage = "https://github.com/ichsanulamal/snsr"
