[project]
name = "agentutil"
version = "0.1.15"
description = "Basic classes and utils for developing agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.1",
    "flake8>=7.2.0",
    "langchain>=0.3.25",
    "pydantic>=2.11.4",
]
