[project]
name = "mseep-gitingest-mcp"
version = "0.1.2"
description = "Gitingest MCP server that provides Github repository info including file content, directory structure and other metadata"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gitingest>=0.1.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
gitingest-mcp = "gitingest_mcp.server:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/gitingest_mcp",
]
