[project]
name = "mseep-adb-mysql-mcp-server"
version = "1.0.2"
description = "An offical mcp server for Adb MySQL of Alibaba Cloud"
readme = "README.md"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.5.0",
    "pymysql>=1.1.1",
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
adb-mysql-mcp-server = "adb_mysql_mcp_server:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets]
