defaults:
  - cfg
  - model: llava-7b
  - trainer: pretrain
  - inference: default
  - dataset: llava-pretrain
  - override hydra/job_logging: rich
  - _self_

hydra:
  job:
    chdir: true
  job_logging:
    root:
      level: INFO
