[project]
name = "mseep-mcp-server-calculator"
version = "0.2.2"
description = "A Model Context Protocol server for calculating"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
keywords = [
    "mcp",
    "llm",
    "math",
    "calculator",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "mcp>=1.4.1",
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.license]
text = "MIT"

[project.scripts]
mcp-server-calculator = "mcp_server_calculator:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets]
