[project]
name = "mseep-qmt-mcp-server"
version = "0.1.2"
description = "MCP Server for QMT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.6.0",
    "pyyaml>=6.0.2",
    "xtquant>=241014.1.2",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
