[project]
name = "mseep-mcp-server-motherduck"
version = "0.1.2"
description = "A MCP server for MotherDuck and local DuckDB"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.3.0",
    "duckdb==1.2.2",
    "pandas>=2.0.0",
    "tabulate>=0.9.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
mcp-server-motherduck = "mcp_server_motherduck:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets]
