[project]
name = "mseep-mcp2lambda"
version = "0.1.2"
description = "MCP2Lambda - A bridge between MCP clients and AWS Lambda functions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.0",
    "mcp==1.3.0",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[tool.uv.workspace]
members = [
    "mcp_bedrock",
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
