[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "mseep-mcp-salesforce-connector"
version = "0.1.5"
description = "A Model Context Protocol (MCP) server implementation for Salesforce integration"
readme = "README.md"
requires-python = ">=3.10"
keywords = [
    "mcp",
    "llm",
    "salesforce",
]
dependencies = [
    "mcp",
    "simple-salesforce",
    "python-dotenv",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.license]
text = "MIT"

[project.scripts]
salesforce = "src.salesforce:main"

[tool.hatch.build.targets.wheel]
packages = [
    "src",
]
