[project]
name = "azure-storage-helper"
version = "0.3.2"
description = "Azure Storage Helper"
readme = "README.md"
authors = [
    { name = "황규본", email = "hwanggb1229@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "azure-identity>=1.21.0",
    "azure-storage-blob>=12.25.1",
    "azure-storage-file-datalake>=12.20.0",
    "joblib>=1.4.2",
    "pandas>=2.0.3",
    "pyarrow>=17.0.0",
    "pyyaml>=6.0.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/azure"]
include = [
  "src/azure/**",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
