[project]
name = "easier-data"
version = "0.1.5"
description = "Python package for managing data and plotting easier "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "black[jupyter]>=25.1.0",
]
