[build-system]
requires = ["setuptools>=75.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-server-zhxg-search"
version = "0.1.1"
description = "智慧星光互联网开源信息搜索工具"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "asyncio>=3.4.3",
    "mcp>=1.9.0",
    "openai>=1.79.0",
    "openai-agents>=0.0.15",
    "pydantic>=2.11.4",
    "typing>=3.10.0.0",
]

[project.scripts]
mcp-server-zhxg-search = "mcp_server_zhxg_search:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]