[project]
name = "mseep-modal-server"
version = "0.1.2"
description = ""
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.1.1",
    "python-dotenv>=1.0.1",
    "modal>=0.67",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
modal-server = "modal_server:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets]
