[build-system]
requires = ["setuptools>=60", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datatailr"
version = "0.1.0"
description = "The datatailr package"
readme = "README.md"
requires-python = ">=3.7"
authors = [
  { name="Datatailr", email="pypi@datatailr.com" }
]
license = { text = "MIT" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
