[project]
name = "mseep-aranet4-mcp-server"
version = "0.1.2"
description = "Simple MCP server to manage your aranet4 device and local db."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pillow>=11.1.0",
    "aranet4>=2.5.1",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "tzlocal>=5.3.1",
    "pyyaml>=6.0.2",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
