[build-system]
requires = ["setuptools>=68.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-git-assistant"
version = "1.0.2"
authors = [
    {name = "Luis Gonzalez", email = "luisgnzhdz@gmail.com"},
]
description = "Asistente inteligente para atuomatizar tareas de Git y GitHub"
readme = "README.md" 
license = "MIT"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "scikit-learn",
    "numpy",
    "joblib",
]

[project.scripts]
ai-git-assistant = "ai_git_assistant.__main__:main"

[project.urls]
"Homepage" = "https://github.com/LuisGH28/git_assitant"

