[project]
name = "mseep-databutton-app-mcp"
version = "0.1.20"
description = "Call your Databutton app endpoints as LLM tools with MCP"
readme = "README.md"
license = "MIT"
license-files = [
    "LICENSE",
]
keywords = [
    "databutton",
    "app",
    "mcp",
    "llm",
    "tool",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.11"
dependencies = [
    "certifi>=2025.1.31",
    "httpx>=0.28.1",
    "websockets>=15.0.1",
]
authors = [
    { name = "mseep", email = "support@skydeck.ai" },
]
maintainers = [
    { name = "mseep", email = "support@skydeck.ai" },
]

[project.scripts]
databutton-app-mcp = "databutton_app_mcp.__main__:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
    "src/databutton_app_mcp",
]
